# app-deployment.yaml

# Define the Deployment for your application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-agb-deployment
  labels:
    app: bankapp-agb-app   # Unique label for the Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-agb-app
  template:
    metadata:
      labels:
        app: bankapp-agb-app
    spec:
      containers:
        - name: bankapp-agb-container
          image: borkaramar10/banking_app:latest
          ports:
            - containerPort: 8084

# Define a Service to expose your app internally within the cluster
apiVersion: v1
kind: Service
metadata:
  name: bankapp-agb-np-service
  labels:
    app: bankapp-agb-app   # Unique label for the Service
spec:
  selector:
    app: bankapp-agb-app

  type: NodePort
  ports:
    - nodePort: 31002
      port: 8084
      targetPort: 8084
